version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - unconvert
  settings:
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 25
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - golint
          - unused
        path: internal/mocks/
      - linters:
          - golint
        path: api/gen/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - api/gen/
