services:
  postgres:
    image: postgres:15-alpine
    container_name: vocnet-postgres
    environment:
      POSTGRES_DB: vocnet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  vocnet:
    image: ghcr.io/eslsoft/vocnet:latest
    container_name: vocnet-server
    environment:
      DB_DSN: postgres://postgres:postgres@postgres:5432/vocnet?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
