version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rockd-postgres
    environment:
      POSTGRES_DB: rockd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rockd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rockd-server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rockd
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSLMODE: disable
      SERVER_HOST: 0.0.0.0
      GRPC_PORT: 9090
      HTTP_PORT: 8080
      LOG_LEVEL: info
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: