// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file dict/v1/phrase.proto (package dict.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Language } from "../../common/v1/types_pb";
import { file_common_v1_types } from "../../common/v1/types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dict/v1/phrase.proto.
 */
export const file_dict_v1_phrase: GenFile = /*@__PURE__*/
  fileDesc("ChRkaWN0L3YxL3BocmFzZS5wcm90bxIHZGljdC52MSJJCgZQaHJhc2USCgoCaWQYASABKAMSDAoEdGV4dBgCIAEoCRIlCghsYW5ndWFnZRgDIAEoDjITLmNvbW1vbi52MS5MYW5ndWFnZTITChFEaWN0UGhyYXNlU2VydmljZUKJAQoLY29tLmRpY3QudjFCC1BocmFzZVByb3RvUAFaMGdpdGh1Yi5jb20vZXNsc29mdC92b2NuZXQvYXBpL2dlbi9kaWN0L3YxO2RpY3R2MaICA0RYWKoCB0RpY3QuVjHKAgdEaWN0XFYx4gITRGljdFxWMVxHUEJNZXRhZGF0YeoCCERpY3Q6OlYxYgZwcm90bzM", [file_common_v1_types]);

/**
 * @generated from message dict.v1.Phrase
 */
export type Phrase = Message<"dict.v1.Phrase"> & {
  /**
   * Auto-increment ID (CRUD only)
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Surface form of the phrase
   *
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * Language of the phrase
   *
   * @generated from field: common.v1.Language language = 3;
   */
  language: Language;
};

/**
 * Describes the message dict.v1.Phrase.
 * Use `create(PhraseSchema)` to create a new message.
 */
export const PhraseSchema: GenMessage<Phrase> = /*@__PURE__*/
  messageDesc(file_dict_v1_phrase, 0);

/**
 * @generated from service dict.v1.DictPhraseService
 */
export const DictPhraseService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_dict_v1_phrase, 0);

