// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file vocnet/v1/vocnet.proto (package vocnet.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Language, RelationType } from "../../common/v1/types_pb";
import { file_common_v1_types } from "../../common/v1/types_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Sentence } from "../../dict/v1/word_pb";
import { file_dict_v1_word } from "../../dict/v1/word_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vocnet/v1/vocnet.proto.
 */
export const file_vocnet_v1_vocnet: GenFile = /*@__PURE__*/
  fileDesc("ChZ2b2NuZXQvdjEvdm9jbmV0LnByb3RvEgl2b2NuZXQudjEiaAoIVXNlcldvcmQSCgoCaWQYASABKAMSJQoEc3BlYxgCIAEoCzIXLnZvY25ldC52MS5Vc2VyV29yZFNwZWMSKQoGc3RhdHVzGAMgASgLMhkudm9jbmV0LnYxLlVzZXJXb3JkU3RhdHVzIs0BCgxVc2VyV29yZFNwZWMSDAoEd29yZBgBIAEoCRIlCghsYW5ndWFnZRgCIAEoDjITLmNvbW1vbi52MS5MYW5ndWFnZRIVCg1tYXN0ZXJ5X2xldmVsGAMgASgFEi4KCXJlbGF0aW9ucxgFIAMoCzIbLnZvY25ldC52MS5Vc2VyV29yZFJlbGF0aW9uEiQKCXNlbnRlbmNlcxgGIAMoCzIRLmRpY3QudjEuU2VudGVuY2USDAoEdGFncxgHIAMoCRINCgVub3RlcxgIIAMoCSL3AQoOVXNlcldvcmRTdGF0dXMSLAoHbWFzdGVyeRgDIAEoCzIbLnZvY25ldC52MS5NYXN0ZXJ5QnJlYWtkb3duEi4KDXJldmlld190aW1pbmcYBCABKAsyFy52b2NuZXQudjEuUmV2aWV3VGltaW5nEhMKC3F1ZXJ5X2NvdW50GAUgASgDEhIKCmNyZWF0ZWRfYnkYFCABKAkSLgoKY3JlYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgWIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiYwoQTWFzdGVyeUJyZWFrZG93bhIOCgZsaXN0ZW4YASABKAUSDAoEcmVhZBgCIAEoBRINCgVzcGVsbBgDIAEoBRIRCglwcm9ub3VuY2UYBCABKAUSDwoHb3ZlcmFsbBgGIAEoBSKhAQoMUmV2aWV3VGltaW5nEjIKDmxhc3RfcmV2aWV3X2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIyCg5uZXh0X3Jldmlld19hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFQoNaW50ZXJ2YWxfZGF5cxgDIAEoBRISCgpmYWlsX2NvdW50GAQgASgFIr4BChBVc2VyV29yZFJlbGF0aW9uEgwKBHdvcmQYASABKAkSLgoNcmVsYXRpb25fdHlwZRgCIAEoDjIXLmNvbW1vbi52MS5SZWxhdGlvblR5cGUSDAoEbm90ZRgDIAEoCRIuCgpjcmVhdGVkX2F0GBUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEKXAQoNY29tLnZvY25ldC52MUILVm9jbmV0UHJvdG9QAVo0Z2l0aHViLmNvbS9lc2xzb2Z0L3ZvY25ldC9hcGkvZ2VuL3ZvY25ldC92MTt2b2NuZXR2MaICA1ZYWKoCCVZvY25ldC5WMcoCCVZvY25ldFxWMeICFVZvY25ldFxWMVxHUEJNZXRhZGF0YeoCClZvY25ldDo6VjFiBnByb3RvMw", [file_common_v1_types, file_google_protobuf_timestamp, file_dict_v1_word]);

/**
 * User's personal word record with learning context
 *
 * @generated from message vocnet.v1.UserWord
 */
export type UserWord = Message<"vocnet.v1.UserWord"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: vocnet.v1.UserWordSpec spec = 2;
   */
  spec?: UserWordSpec;

  /**
   * @generated from field: vocnet.v1.UserWordStatus status = 3;
   */
  status?: UserWordStatus;
};

/**
 * Describes the message vocnet.v1.UserWord.
 * Use `create(UserWordSchema)` to create a new message.
 */
export const UserWordSchema: GenMessage<UserWord> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 0);

/**
 * Spec is user-provided data for the word
 *
 * @generated from message vocnet.v1.UserWordSpec
 */
export type UserWordSpec = Message<"vocnet.v1.UserWordSpec"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * Language of the word
   *
   * @generated from field: common.v1.Language language = 2;
   */
  language: Language;

  /**
   * Mastery level (0-5), self-assessed by user
   *
   * @generated from field: int32 mastery_level = 3;
   */
  masteryLevel: number;

  /**
   * Relationships to other words
   *
   * @generated from field: repeated vocnet.v1.UserWordRelation relations = 5;
   */
  relations: UserWordRelation[];

  /**
   * Contextual example sentences
   *
   * @generated from field: repeated dict.v1.Sentence sentences = 6;
   */
  sentences: Sentence[];

  /**
   * User-defined tags
   *
   * @generated from field: repeated string tags = 7;
   */
  tags: string[];

  /**
   * User's personal notes
   *
   * @generated from field: repeated string notes = 8;
   */
  notes: string[];
};

/**
 * Describes the message vocnet.v1.UserWordSpec.
 * Use `create(UserWordSpecSchema)` to create a new message.
 */
export const UserWordSpecSchema: GenMessage<UserWordSpec> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 1);

/**
 * Status is read-only, maintained by the system
 *
 * @generated from message vocnet.v1.UserWordStatus
 */
export type UserWordStatus = Message<"vocnet.v1.UserWordStatus"> & {
  /**
   * Detailed mastery scores
   *
   * @generated from field: vocnet.v1.MasteryBreakdown mastery = 3;
   */
  mastery?: MasteryBreakdown;

  /**
   * Review scheduling info
   *
   * @generated from field: vocnet.v1.ReviewTiming review_timing = 4;
   */
  reviewTiming?: ReviewTiming;

  /**
   * How many times user looked up this word
   *
   * @generated from field: int64 query_count = 5;
   */
  queryCount: bigint;

  /**
   * Owner username (read-only)
   *
   * @generated from field: string created_by = 20;
   */
  createdBy: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 21;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 22;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message vocnet.v1.UserWordStatus.
 * Use `create(UserWordStatusSchema)` to create a new message.
 */
export const UserWordStatusSchema: GenMessage<UserWordStatus> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 2);

/**
 * Mastery breakdown for different skills
 *
 * @generated from message vocnet.v1.MasteryBreakdown
 */
export type MasteryBreakdown = Message<"vocnet.v1.MasteryBreakdown"> & {
  /**
   * Listening mastery (0-5)
   *
   * @generated from field: int32 listen = 1;
   */
  listen: number;

  /**
   * Reading mastery (0-5)
   *
   * @generated from field: int32 read = 2;
   */
  read: number;

  /**
   * Spelling mastery (0-5)
   *
   * @generated from field: int32 spell = 3;
   */
  spell: number;

  /**
   * Pronunciation mastery (0-5)
   *
   * @generated from field: int32 pronounce = 4;
   */
  pronounce: number;

  /**
   * Overall mastery score (0-500, stored as *100)
   *
   * @generated from field: int32 overall = 6;
   */
  overall: number;
};

/**
 * Describes the message vocnet.v1.MasteryBreakdown.
 * Use `create(MasteryBreakdownSchema)` to create a new message.
 */
export const MasteryBreakdownSchema: GenMessage<MasteryBreakdown> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 3);

/**
 * Review timing information
 *
 * @generated from message vocnet.v1.ReviewTiming
 */
export type ReviewTiming = Message<"vocnet.v1.ReviewTiming"> & {
  /**
   * @generated from field: google.protobuf.Timestamp last_review_at = 1;
   */
  lastReviewAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp next_review_at = 2;
   */
  nextReviewAt?: Timestamp;

  /**
   * Current review interval
   *
   * @generated from field: int32 interval_days = 3;
   */
  intervalDays: number;

  /**
   * Consecutive failure count
   *
   * @generated from field: int32 fail_count = 4;
   */
  failCount: number;
};

/**
 * Describes the message vocnet.v1.ReviewTiming.
 * Use `create(ReviewTimingSchema)` to create a new message.
 */
export const ReviewTimingSchema: GenMessage<ReviewTiming> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 4);

/**
 * Word-to-word relationship for building vocabulary networks
 *
 * @generated from message vocnet.v1.UserWordRelation
 */
export type UserWordRelation = Message<"vocnet.v1.UserWordRelation"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * Type of relationship
   *
   * @generated from field: common.v1.RelationType relation_type = 2;
   */
  relationType: RelationType;

  /**
   * User's note about this relation
   *
   * @generated from field: string note = 3;
   */
  note: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 21;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 22;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message vocnet.v1.UserWordRelation.
 * Use `create(UserWordRelationSchema)` to create a new message.
 */
export const UserWordRelationSchema: GenMessage<UserWordRelation> = /*@__PURE__*/
  messageDesc(file_vocnet_v1_vocnet, 5);

