// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: learning/v1/learning_service.proto

package learningv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectLexeme request - main API for adding lexemes to user vocabulary
type CollectLexemeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lexeme        *LearnedLexeme         `protobuf:"bytes,1,opt,name=lexeme,proto3" json:"lexeme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectLexemeRequest) Reset() {
	*x = CollectLexemeRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLexemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLexemeRequest) ProtoMessage() {}

func (x *CollectLexemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLexemeRequest.ProtoReflect.Descriptor instead.
func (*CollectLexemeRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{0}
}

func (x *CollectLexemeRequest) GetLexeme() *LearnedLexeme {
	if x != nil {
		return x.Lexeme
	}
	return nil
}

// UpdateLearnedLexemeMasteryRequest request
type UpdateMasteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LexemeId      int64                  `protobuf:"varint,1,opt,name=lexeme_id,json=lexemeId,proto3" json:"lexeme_id,omitempty"`
	Mastery       *MasteryBreakdown      `protobuf:"bytes,2,opt,name=mastery,proto3" json:"mastery,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasteryRequest) Reset() {
	*x = UpdateMasteryRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasteryRequest) ProtoMessage() {}

func (x *UpdateMasteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasteryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasteryRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMasteryRequest) GetLexemeId() int64 {
	if x != nil {
		return x.LexemeId
	}
	return 0
}

func (x *UpdateMasteryRequest) GetMastery() *MasteryBreakdown {
	if x != nil {
		return x.Mastery
	}
	return nil
}

func (x *UpdateMasteryRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// ListLearnedLexemesRequest request with comprehensive filtering
type ListLearnedLexemesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination parameters
	Pagination *v1.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// filtering options using CEL expressions
	Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// ordering options. e.g. "lexeme asc", "mastery.overall desc"
	OrderBy       string `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedLexemesRequest) Reset() {
	*x = ListLearnedLexemesRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedLexemesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedLexemesRequest) ProtoMessage() {}

func (x *ListLearnedLexemesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedLexemesRequest.ProtoReflect.Descriptor instead.
func (*ListLearnedLexemesRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListLearnedLexemesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedLexemesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListLearnedLexemesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListLearnedLexemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Lexemes       []*LearnedLexeme       `protobuf:"bytes,2,rep,name=lexemes,proto3" json:"lexemes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedLexemesResponse) Reset() {
	*x = ListLearnedLexemesResponse{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedLexemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedLexemesResponse) ProtoMessage() {}

func (x *ListLearnedLexemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedLexemesResponse.ProtoReflect.Descriptor instead.
func (*ListLearnedLexemesResponse) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearnedLexemesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedLexemesResponse) GetLexemes() []*LearnedLexeme {
	if x != nil {
		return x.Lexemes
	}
	return nil
}

var File_learning_v1_learning_service_proto protoreflect.FileDescriptor

const file_learning_v1_learning_service_proto_rawDesc = "" +
	"\n" +
	"\"learning/v1/learning_service.proto\x12\vlearning.v1\x1a\x15common/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1alearning/v1/learning.proto\x1a\x17validate/validate.proto\"J\n" +
	"\x14CollectLexemeRequest\x122\n" +
	"\x06lexeme\x18\x01 \x01(\v2\x1a.learning.v1.LearnedLexemeR\x06lexeme\"\x8b\x01\n" +
	"\x14UpdateMasteryRequest\x12$\n" +
	"\tlexeme_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\blexemeId\x127\n" +
	"\amastery\x18\x02 \x01(\v2\x1d.learning.v1.MasteryBreakdownR\amastery\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\x8c\x01\n" +
	"\x19ListLearnedLexemesRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"\x91\x01\n" +
	"\x1aListLearnedLexemesResponse\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x124\n" +
	"\alexemes\x18\x02 \x03(\v2\x1a.learning.v1.LearnedLexemeR\alexemes2\xe1\x02\n" +
	"\x0fLearningService\x12P\n" +
	"\rCollectLexeme\x12!.learning.v1.CollectLexemeRequest\x1a\x1a.learning.v1.LearnedLexeme\"\x00\x12A\n" +
	"\x0fUncollectLexeme\x12\x14.common.v1.IDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\x12ListLearnedLexemes\x12&.learning.v1.ListLearnedLexemesRequest\x1a'.learning.v1.ListLearnedLexemesResponse\"\x00\x12P\n" +
	"\rUpdateMastery\x12!.learning.v1.UpdateMasteryRequest\x1a\x1a.learning.v1.LearnedLexeme\"\x00B\xae\x01\n" +
	"\x0fcom.learning.v1B\x14LearningServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_learning_service_proto_rawDescOnce sync.Once
	file_learning_v1_learning_service_proto_rawDescData []byte
)

func file_learning_v1_learning_service_proto_rawDescGZIP() []byte {
	file_learning_v1_learning_service_proto_rawDescOnce.Do(func() {
		file_learning_v1_learning_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)))
	})
	return file_learning_v1_learning_service_proto_rawDescData
}

var file_learning_v1_learning_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_learning_v1_learning_service_proto_goTypes = []any{
	(*CollectLexemeRequest)(nil),       // 0: learning.v1.CollectLexemeRequest
	(*UpdateMasteryRequest)(nil),       // 1: learning.v1.UpdateMasteryRequest
	(*ListLearnedLexemesRequest)(nil),  // 2: learning.v1.ListLearnedLexemesRequest
	(*ListLearnedLexemesResponse)(nil), // 3: learning.v1.ListLearnedLexemesResponse
	(*LearnedLexeme)(nil),              // 4: learning.v1.LearnedLexeme
	(*MasteryBreakdown)(nil),           // 5: learning.v1.MasteryBreakdown
	(*v1.PaginationRequest)(nil),       // 6: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),      // 7: common.v1.PaginationResponse
	(*v1.IDRequest)(nil),               // 8: common.v1.IDRequest
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_learning_v1_learning_service_proto_depIdxs = []int32{
	4, // 0: learning.v1.CollectLexemeRequest.lexeme:type_name -> learning.v1.LearnedLexeme
	5, // 1: learning.v1.UpdateMasteryRequest.mastery:type_name -> learning.v1.MasteryBreakdown
	6, // 2: learning.v1.ListLearnedLexemesRequest.pagination:type_name -> common.v1.PaginationRequest
	7, // 3: learning.v1.ListLearnedLexemesResponse.pagination:type_name -> common.v1.PaginationResponse
	4, // 4: learning.v1.ListLearnedLexemesResponse.lexemes:type_name -> learning.v1.LearnedLexeme
	0, // 5: learning.v1.LearningService.CollectLexeme:input_type -> learning.v1.CollectLexemeRequest
	8, // 6: learning.v1.LearningService.UncollectLexeme:input_type -> common.v1.IDRequest
	2, // 7: learning.v1.LearningService.ListLearnedLexemes:input_type -> learning.v1.ListLearnedLexemesRequest
	1, // 8: learning.v1.LearningService.UpdateMastery:input_type -> learning.v1.UpdateMasteryRequest
	4, // 9: learning.v1.LearningService.CollectLexeme:output_type -> learning.v1.LearnedLexeme
	9, // 10: learning.v1.LearningService.UncollectLexeme:output_type -> google.protobuf.Empty
	3, // 11: learning.v1.LearningService.ListLearnedLexemes:output_type -> learning.v1.ListLearnedLexemesResponse
	4, // 12: learning.v1.LearningService.UpdateMastery:output_type -> learning.v1.LearnedLexeme
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_learning_v1_learning_service_proto_init() }
func file_learning_v1_learning_service_proto_init() {
	if File_learning_v1_learning_service_proto != nil {
		return
	}
	file_learning_v1_learning_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_v1_learning_service_proto_goTypes,
		DependencyIndexes: file_learning_v1_learning_service_proto_depIdxs,
		MessageInfos:      file_learning_v1_learning_service_proto_msgTypes,
	}.Build()
	File_learning_v1_learning_service_proto = out.File
	file_learning_v1_learning_service_proto_goTypes = nil
	file_learning_v1_learning_service_proto_depIdxs = nil
}
