// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file common/v1/types.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";
import { file_validate_validate } from "../../validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/types.proto.
 */
export const file_common_v1_types: GenFile = /*@__PURE__*/
  fileDesc("ChVjb21tb24vdjEvdHlwZXMucHJvdG8SCWNvbW1vbi52MSIgCglJRFJlcXVlc3QSEwoCaWQYASABKANCB/pCBCICIAAiNwoRUGFnaW5hdGlvblJlcXVlc3QSDwoHcGFnZV9ubxgBIAEoBRIRCglwYWdlX3NpemUYAiABKAUiNAoSUGFnaW5hdGlvblJlc3BvbnNlEg0KBXRvdGFsGAEgASgFEg8KB3BhZ2Vfbm8YAiABKAUqvAEKCExhbmd1YWdlEhgKFExBTkdVQUdFX1VOU1BFQ0lGSUVEEAASFAoQTEFOR1VBR0VfRU5HTElTSBABEhQKEExBTkdVQUdFX0NISU5FU0UQAhIUChBMQU5HVUFHRV9TUEFOSVNIEAMSEwoPTEFOR1VBR0VfRlJFTkNIEAQSEwoPTEFOR1VBR0VfR0VSTUFOEAUSFQoRTEFOR1VBR0VfSkFQQU5FU0UQBhITCg9MQU5HVUFHRV9LT1JFQU4QByqtAgoMUmVsYXRpb25UeXBlEh0KGVJFTEFUSU9OX1RZUEVfVU5TUEVDSUZJRUQQABIZChVSRUxBVElPTl9UWVBFX1NZTk9OWU0QARIZChVSRUxBVElPTl9UWVBFX0FOVE9OWU0QAhIaChZSRUxBVElPTl9UWVBFX0hZUEVSTllNEAMSGQoVUkVMQVRJT05fVFlQRV9IWVBPTllNEAQSHQoZUkVMQVRJT05fVFlQRV9BU1NPQ0lBVElPThAFEh4KGlJFTEFUSU9OX1RZUEVfQ0FVU0VfRUZGRUNUEAYSHAoYUkVMQVRJT05fVFlQRV9QQVJUX1dIT0xFEAcSGgoWUkVMQVRJT05fVFlQRV9NTkVNT05JQxAKEhgKFFJFTEFUSU9OX1RZUEVfQ1VTVE9NEGQqsQEKClNvdXJjZVR5cGUSGwoXU09VUkNFX1RZUEVfVU5TUEVDSUZJRUQQABIUChBTT1VSQ0VfVFlQRV9CT09LEAESEwoPU09VUkNFX1RZUEVfV0VCEAISFQoRU09VUkNFX1RZUEVfQVVESU8QAxIVChFTT1VSQ0VfVFlQRV9WSURFTxAEEhYKElNPVVJDRV9UWVBFX01BTlVBTBAFEhUKEVNPVVJDRV9UWVBFX09USEVSEApCxwIKDWNvbS5jb21tb24udjFCClR5cGVzUHJvdG9QAVo0Z2l0aHViLmNvbS9lc2xzb2Z0L3ZvY25ldC9hcGkvZ2VuL2NvbW1vbi92MTtjb21tb252MaICA0NYWKoCCUNvbW1vbi5WMcoCCUNvbW1vblxWMeICFUNvbW1vblxWMVxHUEJNZXRhZGF0YeoCCkNvbW1vbjo6VjGSQa0BEoIBCgpWb2NuZXQgQVBJEjZWb2NuZXQgQVBJIGZvciB2b2NhYnVsYXJ5IGxlYXJuaW5nIGFuZCB3b3JkIG1hbmFnZW1lbnQiNwoSVm9jbmV0IEFQSSBTdXBwb3J0EiFodHRwczovL2dpdGh1Yi5jb20vZXNsc29mdC92b2NuZXQyAzEuMCoCAQIyEGFwcGxpY2F0aW9uL2pzb246EGFwcGxpY2F0aW9uL2pzb25iBnByb3RvMw", [file_protoc_gen_openapiv2_options_annotations, file_validate_validate]);

/**
 * ID request message
 *
 * @generated from message common.v1.IDRequest
 */
export type IDRequest = Message<"common.v1.IDRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message common.v1.IDRequest.
 * Use `create(IDRequestSchema)` to create a new message.
 */
export const IDRequestSchema: GenMessage<IDRequest> = /*@__PURE__*/
  messageDesc(file_common_v1_types, 0);

/**
 * Pagination request parameters
 *
 * @generated from message common.v1.PaginationRequest
 */
export type PaginationRequest = Message<"common.v1.PaginationRequest"> & {
  /**
   * Number of items to return (default: 20, max: 100)
   *
   * @generated from field: int32 page_no = 1;
   */
  pageNo: number;

  /**
   * Number of items to skip (default: 0)
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;
};

/**
 * Describes the message common.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_common_v1_types, 1);

/**
 * Pagination response metadata
 *
 * @generated from message common.v1.PaginationResponse
 */
export type PaginationResponse = Message<"common.v1.PaginationResponse"> & {
  /**
   * Total number of items
   *
   * @generated from field: int32 total = 1;
   */
  total: number;

  /**
   * Current page number (calculated from offset/limit)
   *
   * @generated from field: int32 page_no = 2;
   */
  pageNo: number;
};

/**
 * Describes the message common.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_common_v1_types, 2);

/**
 * Supported languages
 *
 * @generated from enum common.v1.Language
 */
export enum Language {
  /**
   * @generated from enum value: LANGUAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * en
   *
   * @generated from enum value: LANGUAGE_ENGLISH = 1;
   */
  ENGLISH = 1,

  /**
   * zh
   *
   * @generated from enum value: LANGUAGE_CHINESE = 2;
   */
  CHINESE = 2,

  /**
   * es
   *
   * @generated from enum value: LANGUAGE_SPANISH = 3;
   */
  SPANISH = 3,

  /**
   * fr
   *
   * @generated from enum value: LANGUAGE_FRENCH = 4;
   */
  FRENCH = 4,

  /**
   * de
   *
   * @generated from enum value: LANGUAGE_GERMAN = 5;
   */
  GERMAN = 5,

  /**
   * ja
   *
   * @generated from enum value: LANGUAGE_JAPANESE = 6;
   */
  JAPANESE = 6,

  /**
   * ko
   *
   * @generated from enum value: LANGUAGE_KOREAN = 7;
   */
  KOREAN = 7,
}

/**
 * Describes the enum common.v1.Language.
 */
export const LanguageSchema: GenEnum<Language> = /*@__PURE__*/
  enumDesc(file_common_v1_types, 0);

/**
 * Word relation types for building vocabulary networks
 *
 * @generated from enum common.v1.RelationType
 */
export enum RelationType {
  /**
   * @generated from enum value: RELATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 同义词
   *
   * @generated from enum value: RELATION_TYPE_SYNONYM = 1;
   */
  SYNONYM = 1,

  /**
   * 反义词
   *
   * @generated from enum value: RELATION_TYPE_ANTONYM = 2;
   */
  ANTONYM = 2,

  /**
   * 上位词 (animal->dog)
   *
   * @generated from enum value: RELATION_TYPE_HYPERNYM = 3;
   */
  HYPERNYM = 3,

  /**
   * 下位词 (dog->animal)
   *
   * @generated from enum value: RELATION_TYPE_HYPONYM = 4;
   */
  HYPONYM = 4,

  /**
   * 关联词 (bread->butter)
   *
   * @generated from enum value: RELATION_TYPE_ASSOCIATION = 5;
   */
  ASSOCIATION = 5,

  /**
   * 因果关系 (smoke->cancer)
   *
   * @generated from enum value: RELATION_TYPE_CAUSE_EFFECT = 6;
   */
  CAUSE_EFFECT = 6,

  /**
   * 部分-整体 (wheel->car)
   *
   * @generated from enum value: RELATION_TYPE_PART_WHOLE = 7;
   */
  PART_WHOLE = 7,

  /**
   * 联想/助记 (arbitrary user associations)
   *
   * @generated from enum value: RELATION_TYPE_MNEMONIC = 10;
   */
  MNEMONIC = 10,

  /**
   * 自定义关系 (reserved for extension)
   *
   * @generated from enum value: RELATION_TYPE_CUSTOM = 100;
   */
  CUSTOM = 100,
}

/**
 * Describes the enum common.v1.RelationType.
 */
export const RelationTypeSchema: GenEnum<RelationType> = /*@__PURE__*/
  enumDesc(file_common_v1_types, 1);

/**
 * Source types for sentences and content
 *
 * @generated from enum common.v1.SourceType
 */
export enum SourceType {
  /**
   * @generated from enum value: SOURCE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 书籍
   *
   * @generated from enum value: SOURCE_TYPE_BOOK = 1;
   */
  BOOK = 1,

  /**
   * 网页
   *
   * @generated from enum value: SOURCE_TYPE_WEB = 2;
   */
  WEB = 2,

  /**
   * 音频
   *
   * @generated from enum value: SOURCE_TYPE_AUDIO = 3;
   */
  AUDIO = 3,

  /**
   * 视频
   *
   * @generated from enum value: SOURCE_TYPE_VIDEO = 4;
   */
  VIDEO = 4,

  /**
   * 手动输入
   *
   * @generated from enum value: SOURCE_TYPE_MANUAL = 5;
   */
  MANUAL = 5,

  /**
   * 其他
   *
   * @generated from enum value: SOURCE_TYPE_OTHER = 10;
   */
  OTHER = 10,
}

/**
 * Describes the enum common.v1.SourceType.
 */
export const SourceTypeSchema: GenEnum<SourceType> = /*@__PURE__*/
  enumDesc(file_common_v1_types, 2);

