// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eslsoft/vocnet/internal/infrastructure/database/ent/learnedword"
	"github.com/eslsoft/vocnet/internal/infrastructure/database/ent/predicate"
	"github.com/eslsoft/vocnet/internal/infrastructure/database/ent/word"
)

// LearnedWordQuery is the builder for querying LearnedWord entities.
type LearnedWordQuery struct {
	config
	ctx        *QueryContext
	order      []learnedword.OrderOption
	inters     []Interceptor
	predicates []predicate.LearnedWord
	withWord   *WordQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LearnedWordQuery builder.
func (lwq *LearnedWordQuery) Where(ps ...predicate.LearnedWord) *LearnedWordQuery {
	lwq.predicates = append(lwq.predicates, ps...)
	return lwq
}

// Limit the number of records to be returned by this query.
func (lwq *LearnedWordQuery) Limit(limit int) *LearnedWordQuery {
	lwq.ctx.Limit = &limit
	return lwq
}

// Offset to start from.
func (lwq *LearnedWordQuery) Offset(offset int) *LearnedWordQuery {
	lwq.ctx.Offset = &offset
	return lwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lwq *LearnedWordQuery) Unique(unique bool) *LearnedWordQuery {
	lwq.ctx.Unique = &unique
	return lwq
}

// Order specifies how the records should be ordered.
func (lwq *LearnedWordQuery) Order(o ...learnedword.OrderOption) *LearnedWordQuery {
	lwq.order = append(lwq.order, o...)
	return lwq
}

// QueryWord chains the current query on the "word" edge.
func (lwq *LearnedWordQuery) QueryWord() *WordQuery {
	query := (&WordClient{config: lwq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lwq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(learnedword.Table, learnedword.FieldID, selector),
			sqlgraph.To(word.Table, word.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, learnedword.WordTable, learnedword.WordColumn),
		)
		fromU = sqlgraph.SetNeighbors(lwq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LearnedWord entity from the query.
// Returns a *NotFoundError when no LearnedWord was found.
func (lwq *LearnedWordQuery) First(ctx context.Context) (*LearnedWord, error) {
	nodes, err := lwq.Limit(1).All(setContextOp(ctx, lwq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{learnedword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lwq *LearnedWordQuery) FirstX(ctx context.Context) *LearnedWord {
	node, err := lwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LearnedWord ID from the query.
// Returns a *NotFoundError when no LearnedWord ID was found.
func (lwq *LearnedWordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lwq.Limit(1).IDs(setContextOp(ctx, lwq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{learnedword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lwq *LearnedWordQuery) FirstIDX(ctx context.Context) int {
	id, err := lwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LearnedWord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LearnedWord entity is found.
// Returns a *NotFoundError when no LearnedWord entities are found.
func (lwq *LearnedWordQuery) Only(ctx context.Context) (*LearnedWord, error) {
	nodes, err := lwq.Limit(2).All(setContextOp(ctx, lwq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{learnedword.Label}
	default:
		return nil, &NotSingularError{learnedword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lwq *LearnedWordQuery) OnlyX(ctx context.Context) *LearnedWord {
	node, err := lwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LearnedWord ID in the query.
// Returns a *NotSingularError when more than one LearnedWord ID is found.
// Returns a *NotFoundError when no entities are found.
func (lwq *LearnedWordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lwq.Limit(2).IDs(setContextOp(ctx, lwq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{learnedword.Label}
	default:
		err = &NotSingularError{learnedword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lwq *LearnedWordQuery) OnlyIDX(ctx context.Context) int {
	id, err := lwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LearnedWords.
func (lwq *LearnedWordQuery) All(ctx context.Context) ([]*LearnedWord, error) {
	ctx = setContextOp(ctx, lwq.ctx, ent.OpQueryAll)
	if err := lwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LearnedWord, *LearnedWordQuery]()
	return withInterceptors[[]*LearnedWord](ctx, lwq, qr, lwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lwq *LearnedWordQuery) AllX(ctx context.Context) []*LearnedWord {
	nodes, err := lwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LearnedWord IDs.
func (lwq *LearnedWordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lwq.ctx.Unique == nil && lwq.path != nil {
		lwq.Unique(true)
	}
	ctx = setContextOp(ctx, lwq.ctx, ent.OpQueryIDs)
	if err = lwq.Select(learnedword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lwq *LearnedWordQuery) IDsX(ctx context.Context) []int {
	ids, err := lwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lwq *LearnedWordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lwq.ctx, ent.OpQueryCount)
	if err := lwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lwq, querierCount[*LearnedWordQuery](), lwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lwq *LearnedWordQuery) CountX(ctx context.Context) int {
	count, err := lwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lwq *LearnedWordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lwq.ctx, ent.OpQueryExist)
	switch _, err := lwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lwq *LearnedWordQuery) ExistX(ctx context.Context) bool {
	exist, err := lwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LearnedWordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lwq *LearnedWordQuery) Clone() *LearnedWordQuery {
	if lwq == nil {
		return nil
	}
	return &LearnedWordQuery{
		config:     lwq.config,
		ctx:        lwq.ctx.Clone(),
		order:      append([]learnedword.OrderOption{}, lwq.order...),
		inters:     append([]Interceptor{}, lwq.inters...),
		predicates: append([]predicate.LearnedWord{}, lwq.predicates...),
		withWord:   lwq.withWord.Clone(),
		// clone intermediate query.
		sql:  lwq.sql.Clone(),
		path: lwq.path,
	}
}

// WithWord tells the query-builder to eager-load the nodes that are connected to
// the "word" edge. The optional arguments are used to configure the query builder of the edge.
func (lwq *LearnedWordQuery) WithWord(opts ...func(*WordQuery)) *LearnedWordQuery {
	query := (&WordClient{config: lwq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lwq.withWord = query
	return lwq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LearnedWord.Query().
//		GroupBy(learnedword.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lwq *LearnedWordQuery) GroupBy(field string, fields ...string) *LearnedWordGroupBy {
	lwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LearnedWordGroupBy{build: lwq}
	grbuild.flds = &lwq.ctx.Fields
	grbuild.label = learnedword.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.LearnedWord.Query().
//		Select(learnedword.FieldUserID).
//		Scan(ctx, &v)
func (lwq *LearnedWordQuery) Select(fields ...string) *LearnedWordSelect {
	lwq.ctx.Fields = append(lwq.ctx.Fields, fields...)
	sbuild := &LearnedWordSelect{LearnedWordQuery: lwq}
	sbuild.label = learnedword.Label
	sbuild.flds, sbuild.scan = &lwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LearnedWordSelect configured with the given aggregations.
func (lwq *LearnedWordQuery) Aggregate(fns ...AggregateFunc) *LearnedWordSelect {
	return lwq.Select().Aggregate(fns...)
}

func (lwq *LearnedWordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lwq); err != nil {
				return err
			}
		}
	}
	for _, f := range lwq.ctx.Fields {
		if !learnedword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lwq.path != nil {
		prev, err := lwq.path(ctx)
		if err != nil {
			return err
		}
		lwq.sql = prev
	}
	return nil
}

func (lwq *LearnedWordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LearnedWord, error) {
	var (
		nodes       = []*LearnedWord{}
		_spec       = lwq.querySpec()
		loadedTypes = [1]bool{
			lwq.withWord != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LearnedWord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LearnedWord{config: lwq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lwq.withWord; query != nil {
		if err := lwq.loadWord(ctx, query, nodes, nil,
			func(n *LearnedWord, e *Word) { n.Edges.Word = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lwq *LearnedWordQuery) loadWord(ctx context.Context, query *WordQuery, nodes []*LearnedWord, init func(*LearnedWord), assign func(*LearnedWord, *Word)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LearnedWord)
	for i := range nodes {
		if nodes[i].WordID == nil {
			continue
		}
		fk := *nodes[i].WordID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(word.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "word_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lwq *LearnedWordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lwq.querySpec()
	_spec.Node.Columns = lwq.ctx.Fields
	if len(lwq.ctx.Fields) > 0 {
		_spec.Unique = lwq.ctx.Unique != nil && *lwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lwq.driver, _spec)
}

func (lwq *LearnedWordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(learnedword.Table, learnedword.Columns, sqlgraph.NewFieldSpec(learnedword.FieldID, field.TypeInt))
	_spec.From = lwq.sql
	if unique := lwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lwq.path != nil {
		_spec.Unique = true
	}
	if fields := lwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, learnedword.FieldID)
		for i := range fields {
			if fields[i] != learnedword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if lwq.withWord != nil {
			_spec.Node.AddColumnOnce(learnedword.FieldWordID)
		}
	}
	if ps := lwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lwq *LearnedWordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lwq.driver.Dialect())
	t1 := builder.Table(learnedword.Table)
	columns := lwq.ctx.Fields
	if len(columns) == 0 {
		columns = learnedword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lwq.sql != nil {
		selector = lwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lwq.ctx.Unique != nil && *lwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lwq.predicates {
		p(selector)
	}
	for _, p := range lwq.order {
		p(selector)
	}
	if offset := lwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LearnedWordGroupBy is the group-by builder for LearnedWord entities.
type LearnedWordGroupBy struct {
	selector
	build *LearnedWordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lwgb *LearnedWordGroupBy) Aggregate(fns ...AggregateFunc) *LearnedWordGroupBy {
	lwgb.fns = append(lwgb.fns, fns...)
	return lwgb
}

// Scan applies the selector query and scans the result into the given value.
func (lwgb *LearnedWordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lwgb.build.ctx, ent.OpQueryGroupBy)
	if err := lwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LearnedWordQuery, *LearnedWordGroupBy](ctx, lwgb.build, lwgb, lwgb.build.inters, v)
}

func (lwgb *LearnedWordGroupBy) sqlScan(ctx context.Context, root *LearnedWordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lwgb.fns))
	for _, fn := range lwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lwgb.flds)+len(lwgb.fns))
		for _, f := range *lwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LearnedWordSelect is the builder for selecting fields of LearnedWord entities.
type LearnedWordSelect struct {
	*LearnedWordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lws *LearnedWordSelect) Aggregate(fns ...AggregateFunc) *LearnedWordSelect {
	lws.fns = append(lws.fns, fns...)
	return lws
}

// Scan applies the selector query and scans the result into the given value.
func (lws *LearnedWordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lws.ctx, ent.OpQuerySelect)
	if err := lws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LearnedWordQuery, *LearnedWordSelect](ctx, lws.LearnedWordQuery, lws, lws.inters, v)
}

func (lws *LearnedWordSelect) sqlScan(ctx context.Context, root *LearnedWordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lws.fns))
	for _, fn := range lws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
